let
    Source = Table.Combine({#"Consolidated Learning Needs", #"Consolidated Learning History"}),
    #"Merged Items Categories" = Table.NestedJoin(Source, {"Item ID"}, #"Items Categories", {"Item ID"}, "Items Categories", JoinKind.LeftOuter),
    #"Expanded Items Categories" = Table.ExpandTableColumn(#"Merged Items Categories", "Items Categories", {"KPI Category", "Renewal period", "NRM", "LSM", "SSM"}, {"Items Categories.KPI Category", "Items Categories.Renewal period", "Items Categories.NRM", "Items Categories.LSM", "Items Categories.SSM"}),
    #"Renamed Item Categories" = Table.RenameColumns(#"Expanded Items Categories",{{"Items Categories.KPI Category", "KPI Category"}}),
    #"Replaced Value-NRM Yes" = Table.ReplaceValue(#"Renamed Item Categories","Yes","NRM_Yes",Replacer.ReplaceText,{"Items Categories.NRM"}),
    #"Replaced Value-NRM No" = Table.ReplaceValue(#"Replaced Value-NRM Yes","No","NRM_No",Replacer.ReplaceText,{"Items Categories.NRM"}),
    #"Replaced Value-LSM Yes" = Table.ReplaceValue(#"Replaced Value-NRM No","Yes","LSM_Yes",Replacer.ReplaceText,{"Items Categories.LSM"}),
    #"Replaced Value-LSM No" = Table.ReplaceValue(#"Replaced Value-LSM Yes","No","LSM_No",Replacer.ReplaceText,{"Items Categories.LSM"}),
    #"Replaced Value-SSM Yes" = Table.ReplaceValue(#"Replaced Value-LSM No","Yes","SSM_Yes",Replacer.ReplaceText,{"Items Categories.SSM"}),
    #"Replaced Value-SSM No" = Table.ReplaceValue(#"Replaced Value-SSM Yes","No","SSM_No",Replacer.ReplaceText,{"Items Categories.SSM"}),
    #"Renamed Renewal Period" = Table.RenameColumns(#"Replaced Value-SSM No",{{"Items Categories.Renewal period", "Renewal period"}}),
    #"Merged Learning Needs" = Table.NestedJoin(#"Renamed Renewal Period", {"UID"}, #"Consolidated Learning Needs", {"UID"}, "Consolidated Learning Needs", JoinKind.LeftOuter),
    #"Expanded Consolidated Learning Needs" = Table.ExpandTableColumn(#"Merged Learning Needs", "Consolidated Learning Needs", {"Active User", "Assignment Type"}, {"Consolidated Learning Needs.Active User", "Consolidated Learning Needs.Assignment Type"}),
    #"Changed Type - Renewal Period" = Table.TransformColumnTypes(#"Expanded Consolidated Learning Needs",{{"Renewal period", Int64.Type}}),
    #"Renamed Active User to Exists in Needs" = Table.RenameColumns(#"Changed Type - Renewal Period",{{"Consolidated Learning Needs.Active User", "Exists in Needs Report"}}),
    #"Duplicated Completion Status" = Table.DuplicateColumn(#"Renamed Active User to Exists in Needs", "Completion Status", "Completion Status - Copy"),
    #"Renamed Completion Status" = Table.RenameColumns(#"Duplicated Completion Status",{{"Completion Status", "Detailed Completion Status"}, {"Completion Status - Copy", "Completion Status"}}),
    #"Duplicated Item ID" = Table.DuplicateColumn(#"Renamed Completion Status", "Item ID", "Item ID - Copy"),
    #"Duplicated User ID" = Table.DuplicateColumn(#"Duplicated Item ID", "User ID", "User ID - Copy"),
    #"Merged Columns - Duplicates Test" = Table.CombineColumns(#"Duplicated User ID",{"Item ID - Copy", "User ID - Copy"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Dup Test"),
    #"Merged Queries-eLink People" = Table.NestedJoin(#"Merged Columns - Duplicates Test", {"User ID"}, #"eLink People", {"PERSON_ID"}, "eLink People", JoinKind.LeftOuter),
    #"Expanded eLink People" = Table.ExpandTableColumn(#"Merged Queries-eLink People", "eLink People", {"DEPARTMENT_REGION", "EMAIL"}, {"eLink People.DEPARTMENT_REGION", "eLink People.EMAIL"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Expanded eLink People",{{"eLink People.EMAIL", "EMAIL"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns2", "eLink People.DEPARTMENT_REGION", "eLink People.DEPARTMENT_REGION - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"eLink People.DEPARTMENT_REGION - Copy", "DEPARTMENT_REGION"}}),
    #"Merged Columns-Courses Filter" = Table.CombineColumns(#"Renamed Columns",{"eLink People.DEPARTMENT_REGION", "Items Categories.NRM", "Items Categories.LSM", "Items Categories.SSM"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Courses Filter"),
    #"Replaced Value - Assignment Type - Null to Blank" = Table.ReplaceValue(#"Merged Columns-Courses Filter",null,"",Replacer.ReplaceValue,{"Consolidated Learning Needs.Assignment Type"}),
    #"Replaced Value - Exists in Needs Report - Null to Blank" = Table.ReplaceValue(#"Replaced Value - Assignment Type - Null to Blank",null,"",Replacer.ReplaceValue,{"Exists in Needs Report"}),
    #"Replaced Value Document Read" = Table.ReplaceValue(#"Replaced Value - Exists in Needs Report - Null to Blank","Document Read","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Online Complete" = Table.ReplaceValue(#"Replaced Value Document Read","Online Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Session – Complete" = Table.ReplaceValue(#"Replaced Value Online Complete","Session – Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Assessment Competent" = Table.ReplaceValue(#"Replaced Value Session – Complete","Assessment Competent","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Certificate – Complete" = Table.ReplaceValue(#"Replaced Value Assessment Competent","Certificate – Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Licence – Complete" = Table.ReplaceValue(#"Replaced Value Certificate – Complete","Licence – Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value On the Job Competent" = Table.ReplaceValue(#"Replaced Value Licence – Complete","On the Job Competent","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value SOP/SWP/WI -Competency Under Supervision" = Table.ReplaceValue(#"Replaced Value On the Job Competent","SOP/SWP/WI -Competency Under Supervision","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value SOP/SWP/Work Instruction – Competent" = Table.ReplaceValue(#"Replaced Value SOP/SWP/WI -Competency Under Supervision","SOP/SWP/Work Instruction – Competent","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Program Complete" = Table.ReplaceValue(#"Replaced Value SOP/SWP/Work Instruction – Competent","Program Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Qualification – Complete" = Table.ReplaceValue(#"Replaced Value Program Complete","Qualification – Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Temporary Exemption HR approve" = Table.ReplaceValue(#"Replaced Value Qualification – Complete","Temporary Exemption HR approve","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Null to Blank" = Table.ReplaceValue(#"Replaced Value Temporary Exemption HR approve",null,"",Replacer.ReplaceValue,{"Completion Status"}),
    #"Replaced Value Null to Incomplete" = Table.ReplaceValue(#"Replaced Value Null to Blank",null,"Incomplete",Replacer.ReplaceValue,{"Completion Status"}),
    #"Replaced SOP/SWP/Work Instruction – Incomplete" = Table.ReplaceValue(#"Replaced Value Null to Incomplete","SOP/SWP/Work Instruction – Incomplete","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced On the Job Not Yet Competent" = Table.ReplaceValue(#"Replaced SOP/SWP/Work Instruction – Incomplete","On the Job Not Yet Competent","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Document Not Read" = Table.ReplaceValue(#"Replaced On the Job Not Yet Competent","Document Not Read","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Certificate – Not Yet Complete" = Table.ReplaceValue(#"Replaced Document Not Read","Certificate – Not Yet Complete","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Workshop Complete" = Table.ReplaceValue(#"Replaced Certificate – Not Yet Complete","Workshop Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced SOP/SWP/Work Instruction – T2" = Table.ReplaceValue(#"Replaced Workshop Complete","SOP/SWP/Work Instruction – T2","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Program Partial Attendance" = Table.ReplaceValue(#"Replaced SOP/SWP/Work Instruction – T2","Program Partial Attendance","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced SOP/SWP/Work Instruction – Incompelte" = Table.ReplaceValue(#"Replaced Program Partial Attendance","SOP/SWP/Work Instruction – Incompelte","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Session No Show" = Table.ReplaceValue(#"Replaced SOP/SWP/Work Instruction – Incompelte","Session No Show","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Assessment Not yet competent" = Table.ReplaceValue(#"Replaced Session No Show","Assessment Not yet competent","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Online Incomplete" = Table.ReplaceValue(#"Replaced Assessment Not yet competent","Online Incomplete","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Licence – Expired" = Table.ReplaceValue(#"Replaced Online Incomplete","Licence – Expired","Expired",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Session Partial Attendance" = Table.ReplaceValue(#"Replaced Licence – Expired","Session Partial Attendance","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Course - Complete" = Table.ReplaceValue(#"Replaced Session Partial Attendance","Course - Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Done under supervision" = Table.ReplaceValue(#"Replaced Value Course - Complete","Done under supervision","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced SOP/SWP/Work Instruction – NYC" = Table.ReplaceValue(#"Replaced Done under supervision","SOP/SWP/Work Instruction – NYC","Incomplete",Replacer.ReplaceText,{"Completion Status"}),
    #"Sorted Rows - Completion - Descending" = Table.Sort(#"Replaced SOP/SWP/Work Instruction – NYC",{{"Completion Status", Order.Descending}}),
    #"Removed Duplicates - Dup Test" = Table.Distinct(#"Sorted Rows - Completion - Descending", {"Dup Test"}),
    #"Replaced Value Blank to Incomplete" = Table.ReplaceValue(#"Removed Duplicates - Dup Test","","Incomplete",Replacer.ReplaceValue,{"Completion Status"}),
    #"Duplicated Item ID 2" = Table.DuplicateColumn(#"Replaced Value Blank to Incomplete", "Item ID", "Item ID - Copy"),
    #"Merged Columns" = Table.CombineColumns(#"Duplicated Item ID 2",{"Item ID - Copy", "DEPARTMENT_REGION"},Combiner.CombineTextByDelimiter("_", QuoteStyle.None),"Item Number_Department"),
    #"Changed Type" = Table.TransformColumnTypes(#"Merged Columns",{{"Assignment Date", type date}}),
    #"Replaced Value - SOP/SWP/Work Instruction – T1" = Table.ReplaceValue(#"Changed Type","SOP/SWP/Work Instruction – T1","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value Facilitator/Participant Guide Read" = Table.ReplaceValue(#"Replaced Value - SOP/SWP/Work Instruction – T1","Facilitator/Participant Guide Read","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value Facilitator/Participant Guide Read","Presentation - Viewed","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Program - Complete","Done",Replacer.ReplaceText,{"Completion Status"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","QRG Viewed","Done",Replacer.ReplaceText,{"Completion Status"})
in
    #"Replaced Value2"
